# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

WORKDIR /app

# Copy all project files into container
COPY . .

# Create a setup.cfg to restrict package discovery and avoid multiple top-level packages
RUN echo "[metadata]\nname = mcp2lambda\nversion = 0.1.0\n\n[options]\npy_modules = main" > setup.cfg

# Upgrade pip and install the package without caching
RUN pip install --upgrade pip \
    && pip install . --no-cache-dir

CMD ["python", "main.py"]
