AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample functions for MCP servers.

Resources:

  CustomerInfoFromId:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./customer-info-from-id
      Description: Customer status from "customerId"
      MemorySize: 128
      Timeout: 3
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64

  CustomerIdFromEmail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./customer-id-from-email
      Description: Get customer ID from "email"
      MemorySize: 128
      Timeout: 3
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
        
  RunPythonCode:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./run-python-code
      Description: Run Python code in the 'input_script'. Install modules if 'install_modules' is not an empty list.
      MemorySize: 1024
      Timeout: 60
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64

Outputs:

  CustomerInfoFromId:
    Description: "CustomerInfoFromId Function ARN"
    Value: !GetAtt CustomerInfoFromId.Arn
    
  CustomerIdFromEmail:
    Description: "CustomerIdFromEmail Function ARN"
    Value: !GetAtt CustomerIdFromEmail.Arn